// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import process from "node:process";
import { defineConfig } from "prisma/config";

const { DATABASE_URL } = process.env;

export default defineConfig({
  schema: path.join("src", "shared", "infrastructure", "data", "schema"),
  migrations: {
    path: path.join("src", "shared", "infrastructure", "data", "migrations"),
  },
  datasource: {
    url: DATABASE_URL,
  },
});
