// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: path.join("src", "shared", "infrastructure", "data", "schema"),
  migrations: {
    path: path.join("src", "shared", "infrastructure", "data", "migrations"),
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
